from __future__ import annotations

import json
import os

import pytest

from axio_fusion_api import model_screening
from axio_fusion_api.cli import main as fusion_cli_main
from axio_fusion_api.provider_enrollment import enroll_provider_channels, enroll_runtime_channels
from axio_fusion_api.evaluation import build_fusion_code_test_receipt
from axio_fusion_api.registry import (
    load_registry,
    normalize_profile,
    provider_configuration_source_summary,
)
from axio_fusion_api.schemas import CAPABILITY_AXES, sha256_text


def test_production_registry_loading_rejects_legacy_probe_registry(tmp_path):
    registry_path = tmp_path / "legacy_probe_registry.json"
    registry_path.write_text(
        json.dumps(
            {
                "schema": "axio_fusion_api.registry.v1",
                "models": [
                    {
                        "provider": "legacy-provider",
                        "model": "legacy-model",
                        "health": "available",
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="generated by pre-Fusion screening"):
        load_registry(registry_path, require_prefusion=True)


def test_provider_enrollment_requires_explicit_live_flag_and_restores_config_env(tmp_path, monkeypatch):
    config_path = tmp_path / "channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-responses",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_RESPONSES_BASE_URL",
                        "api_key_env": "FIXTURE_RESPONSES_API_KEY",
                        "models": ["fixture-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("AXIO_FUSION_PROVIDER_CONFIG_FILE", "previous-config.json")

    result = enroll_provider_channels(
        config_path=config_path,
        output_dir=tmp_path / "enrollment",
        live=False,
    )

    assert result["status"] == "blocked"
    assert "live_flag_required_for_channel_enrollment" in result["reason_codes"]
    assert result["anti_leakage_contract"]["raw_api_keys_persisted"] is False
    assert result["anti_leakage_contract"]["raw_provider_urls_persisted"] is False
    assert result["config_source"]["config_file_supplied"] is True
    assert result["config_source"]["config_path_sha256"]
    assert os.environ["AXIO_FUSION_PROVIDER_CONFIG_FILE"] == "previous-config.json"


def test_provider_config_summary_counts_rows_rejected_by_transport_schema(tmp_path, monkeypatch):
    config_path = tmp_path / "invalid_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "valid",
                        "api_format": "responses",
                        "base_url_env": "VALID_BASE_URL",
                        "api_key_env": "VALID_API_KEY",
                        "models": ["valid-model"],
                    },
                    {
                        "provider": "literal-secret-bearing-row",
                        "api_format": "responses",
                        "base_url_env": "https://literal.invalid/v1",
                        "api_key_env": "literal-api-key",
                        "models": ["invalid-model"],
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("AXIO_FUSION_PROVIDER_CONFIG_FILE", str(config_path))

    summary = provider_configuration_source_summary()
    serialized = json.dumps(summary, ensure_ascii=False)

    assert summary["valid_config_file_count"] == 1
    assert summary["provider_config_count"] == 1
    assert summary["invalid_provider_config_count"] == 1
    assert "literal-secret-bearing-row" not in serialized
    assert "literal-api-key" not in serialized
    assert "https://literal.invalid" not in serialized


def test_provider_config_summary_counts_non_object_provider_rows_instead_of_dropping_them(
    tmp_path,
    monkeypatch,
):
    config_path = tmp_path / "malformed_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "valid-channel",
                        "api_format": "responses",
                        "base_url_env": "VALID_CHANNEL_BASE_URL",
                        "api_key_env": "VALID_CHANNEL_API_KEY",
                        "models": ["valid-model"],
                    },
                    "not-a-provider-object",
                    17,
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("AXIO_FUSION_PROVIDER_CONFIG_FILE", str(config_path))

    summary = provider_configuration_source_summary()
    serialized = json.dumps(summary, ensure_ascii=False)

    assert summary["valid_config_file_count"] == 1
    assert summary["provider_config_count"] == 1
    assert summary["invalid_provider_config_count"] == 2
    assert "not-a-provider-object" not in serialized
    assert "valid-channel" not in serialized


def test_provider_config_summary_rejects_unknown_protocol_without_silent_chat_fallback(
    tmp_path, monkeypatch
):
    config_path = tmp_path / "invalid_protocol.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "typo-channel",
                        "api_format": "respones",
                        "base_url_env": "TYPO_BASE_URL",
                        "api_key_env": "TYPO_API_KEY",
                        "models": ["typo-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("AXIO_FUSION_PROVIDER_CONFIG_FILE", str(config_path))

    summary = provider_configuration_source_summary()

    assert summary["provider_config_count"] == 0
    assert summary["invalid_provider_config_count"] == 1
    assert summary["valid_config_file_count"] == 1


def test_provider_manifest_allows_no_auth_channel_without_api_key_env(tmp_path, monkeypatch):
    config_path = tmp_path / "public_gateway.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-public-gateway",
                        "api_format": "chat/completions",
                        "base_url_env": "FIXTURE_PUBLIC_BASE_URL",
                        "auth_scheme": "none",
                        "models": ["public-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("AXIO_FUSION_PROVIDER_CONFIG_FILE", str(config_path))
    monkeypatch.setenv("FIXTURE_PUBLIC_BASE_URL", "https://public-gateway.fixture/v1")
    monkeypatch.delenv("FIXTURE_PUBLIC_API_KEY", raising=False)

    summary = provider_configuration_source_summary()
    profiles = load_registry()
    serialized = json.dumps(summary, ensure_ascii=False)

    assert summary["valid_config_file_count"] == 1
    assert summary["provider_config_count"] == 1
    assert len(profiles) == 1
    assert profiles[0].auth_scheme == "none"
    assert profiles[0].model == "public-model"
    assert "public-gateway.fixture" not in serialized
    assert "public-model" not in serialized


def test_provider_config_summary_cli_is_hash_only_and_accepts_generic_manifest(
    tmp_path,
    monkeypatch,
    capsys,
):
    config_path = tmp_path / "generic_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-gemini-channel",
                        "api_format": "gemini",
                        "base_url_env": "FIXTURE_GEMINI_BASE_URL",
                        "api_key_env": "FIXTURE_GEMINI_API_KEY",
                        "auth_scheme": "x-goog-api-key",
                        "models": ["fixture-gemini-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("FIXTURE_GEMINI_BASE_URL", "https://fixture-gemini.invalid/v1beta")
    monkeypatch.setenv("FIXTURE_GEMINI_API_KEY", "fixture-gemini-secret")

    assert fusion_cli_main(
        ["--provider-config-file", str(config_path), "provider-config-summary"]
    ) == 0
    payload = json.loads(capsys.readouterr().out)
    serialized = json.dumps(payload, ensure_ascii=False)

    assert payload["network_calls_performed"] is False
    assert payload["configured_static_profile_count"] == 1
    assert payload["configured_static_profile_set_sha256"]
    assert payload["runtime_registry_source"] == "provider_config_static_models"
    assert payload["runtime_registry_requires_enrollment"] is False
    assert payload["configuration_sources"]["provider_config_count"] == 1
    assert payload["credential_ready"] is True
    assert payload["credentialed_provider_count"] == 1
    assert payload["credentialed_provider_profile_count"] == 1
    assert payload["credentialed_api_format_counts"] == {"gemini": 1}
    assert payload["live_probe_ready"] is True
    assert payload["live_probe_reason_codes"] == []
    assert os.getenv("AXIO_FUSION_PROVIDER_CONFIG_FILE") is None
    assert "fixture-gemini-channel" not in serialized
    assert "fixture-gemini-model" not in serialized
    assert "fixture-gemini-secret" not in serialized
    assert "https://fixture-gemini.invalid" not in serialized


def test_provider_config_summary_cli_reports_explicit_registry_source(
    tmp_path,
    monkeypatch,
    capsys,
):
    registry_path = tmp_path / "explicit_runtime_registry.json"
    registry_path.write_text(json.dumps({"models": []}), encoding="utf-8")
    for env_name in (
        "AXIO_FUSION_REGISTRY_PATH",
        "AXIO_FUSION_PROVIDER_CONFIG_FILE",
        "AXIO_FUSION_PROVIDER_CONFIGS",
        "AXIO_FUSION_PROVIDERS_JSON",
        "AXIO_FUSION_MODELS",
    ):
        monkeypatch.delenv(env_name, raising=False)

    assert fusion_cli_main(
        ["--registry", str(registry_path), "provider-config-summary"]
    ) == 0
    payload = json.loads(capsys.readouterr().out)
    serialized = json.dumps(payload, ensure_ascii=False)

    assert payload["runtime_registry_source"] == "explicit_registry"
    assert payload["runtime_registry_explicit_argument"] is True
    assert payload["runtime_registry_artifact_available"] is True
    assert payload["runtime_registry_requires_enrollment"] is False
    assert str(registry_path) not in serialized


def test_provider_config_summary_cli_can_write_safe_operator_artifact(
    tmp_path,
    monkeypatch,
    capsys,
):
    config_path = tmp_path / "artifact_channels.json"
    output_path = tmp_path / "provider_config_summary.safe.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-artifact-channel",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_ARTIFACT_BASE_URL",
                        "api_key_env": "FIXTURE_ARTIFACT_API_KEY",
                        "models": ["fixture-artifact-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("FIXTURE_ARTIFACT_BASE_URL", "https://fixture-artifact.invalid/v1")
    monkeypatch.setenv("FIXTURE_ARTIFACT_API_KEY", "fixture-artifact-secret")

    assert fusion_cli_main(
        [
            "--provider-config-file",
            str(config_path),
            "provider-config-summary",
            "--output",
            str(output_path),
        ]
    ) == 0
    assert capsys.readouterr().out == ""
    payload = json.loads(output_path.read_text(encoding="utf-8"))
    serialized = json.dumps(payload, ensure_ascii=False)
    assert payload["credential_ready"] is True
    assert payload["live_probe_ready"] is True
    assert payload["network_calls_performed"] is False
    assert "fixture-artifact-channel" not in serialized
    assert "fixture-artifact-model" not in serialized
    assert "fixture-artifact-secret" not in serialized
    assert "https://fixture-artifact.invalid" not in serialized


def test_cli_serve_can_start_dynamic_manifest_mode_and_write_safe_receipt(
    tmp_path,
    monkeypatch,
):
    config_path = tmp_path / "dynamic_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-dynamic",
                        "api_format": "responses",
                        "base_url": "https://dynamic.example/v1",
                        "api_key": "dynamic-secret",
                        "models": ["dynamic-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    receipt_path = tmp_path / "enrollment_receipt.safe.json"
    observed = {}

    class _FakeServer:
        runtime_channel_enrollment_receipt = {
            "schema": "axio_fusion_api.provider_enrollment.v1",
            "status": "ready",
            "raw_provider_urls_persisted": False,
            "raw_api_keys_persisted": False,
            "secrets_persisted": False,
        }

        def serve_forever(self):
            raise KeyboardInterrupt

        def server_close(self):
            observed["closed"] = True

    def fake_create_runtime_http_server(manifest, **kwargs):
        observed["manifest"] = manifest
        observed["kwargs"] = kwargs
        return _FakeServer()

    monkeypatch.setattr("axio_fusion_api.cli.create_runtime_http_server", fake_create_runtime_http_server)

    assert fusion_cli_main(
        [
            "--provider-config-file",
            str(config_path),
            "serve",
            "--live",
            "--enroll",
            "--enrollment-receipt-output",
            str(receipt_path),
        ]
    ) == 0
    assert observed["manifest"]["providers"][0]["provider"] == "fixture-dynamic"
    assert observed["kwargs"]["enroll"] is True
    assert observed["kwargs"]["live"] is True
    assert observed["closed"] is True
    assert receipt_path.is_file()
    receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
    serialized_receipt = json.dumps(receipt, ensure_ascii=False)
    assert receipt["status"] == "ready"
    assert "dynamic.example" not in serialized_receipt
    assert "dynamic-secret" not in serialized_receipt


def test_cli_serve_dynamic_enrollment_requires_live_flag(tmp_path):
    config_path = tmp_path / "dynamic_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-dynamic",
                        "api_format": "responses",
                        "base_url": "https://dynamic.example/v1",
                        "api_key": "dynamic-secret",
                        "models": ["dynamic-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    try:
        fusion_cli_main(
            [
                "--provider-config-file",
                str(config_path),
                "serve",
                "--enroll",
            ]
        )
    except SystemExit as exc:
        assert "requires --live" in str(exc)
    else:
        raise AssertionError("dynamic enrollment without --live must fail closed")


def test_cli_serve_enrollment_passes_prefusion_admission_configuration(tmp_path, monkeypatch):
    config_path = tmp_path / "prefusion_channels.json"
    config_path.write_text(json.dumps({"providers": []}), encoding="utf-8")
    observed = {}

    class _FakeServer:
        runtime_channel_enrollment_receipt = {"status": "ready"}

        def serve_forever(self):
            raise KeyboardInterrupt

        def server_close(self):
            observed["closed"] = True

    def fake_create_runtime_http_server(manifest, **kwargs):
        observed["manifest"] = manifest
        observed["kwargs"] = kwargs
        return _FakeServer()

    monkeypatch.setattr(
        "axio_fusion_api.cli.create_runtime_http_server",
        fake_create_runtime_http_server,
    )

    assert fusion_cli_main(
        [
            "--provider-config-file",
            str(config_path),
            "serve",
            "--live",
            "--enroll",
            "--prefusion-focus-manifest",
            "focus.json",
            "--prefusion-source-manifest",
            "sources.json",
            "--prefusion-research-agent-config",
            "research-agent.json",
            "--prefusion-research-output",
            "research-output.json",
            "--prefusion-max-models",
            "7",
            "--prefusion-stream-probe-samples",
            "4",
        ]
    ) == 0

    assert observed["kwargs"]["require_prefusion"] is True
    assert observed["kwargs"]["focus_manifest"] == "focus.json"
    assert observed["kwargs"]["source_manifest"] == "sources.json"
    assert observed["kwargs"]["research_agent_config"] == "research-agent.json"
    assert observed["kwargs"]["research_output"] == "research-output.json"
    assert observed["kwargs"]["prefusion_max_models"] == 7
    assert observed["kwargs"]["prefusion_stream_probe_samples"] == 4
    assert observed["closed"] is True


def test_cli_serve_dynamic_discovery_requires_live_flag(tmp_path):
    config_path = tmp_path / "dynamic_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-discovery",
                        "api_format": "responses",
                        "base_url": "https://dynamic.example/v1",
                        "api_key": "dynamic-secret",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    try:
        fusion_cli_main(
            [
                "--provider-config-file",
                str(config_path),
                "serve",
                "--discover",
            ]
        )
    except SystemExit as exc:
        assert "requires --live" in str(exc)
    else:
        raise AssertionError("dynamic discovery without --live must fail closed")


def test_cli_enrollment_binds_global_provider_config_path(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "global_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-global-config",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_GLOBAL_BASE_URL",
                        "api_key_env": "FIXTURE_GLOBAL_API_KEY",
                        "models": ["fixture-global-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("FIXTURE_GLOBAL_BASE_URL", "https://fixture.invalid/v1")
    monkeypatch.setenv("FIXTURE_GLOBAL_API_KEY", "fixture-secret")

    observed = {}

    def fake_enroll_provider_channels(**kwargs):
        observed.update(kwargs)
        return {"status": "blocked", "reason_codes": ["test_only"]}

    monkeypatch.setattr(
        "axio_fusion_api.cli.enroll_provider_channels",
        fake_enroll_provider_channels,
    )
    assert fusion_cli_main(
        [
            "--provider-config-file",
            str(config_path),
            "enroll-providers",
            "--live",
            "--output-dir",
            str(tmp_path / "enrollment"),
        ]
    ) == 2
    capsys.readouterr()
    assert observed["config_path"] == str(config_path)


def test_cli_enrollment_forwards_independent_tool_probe_budget(tmp_path, monkeypatch, capsys):
    config_path = tmp_path / "tool_budget_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-tool-budget",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_TOOL_BUDGET_BASE_URL",
                        "api_key_env": "FIXTURE_TOOL_BUDGET_API_KEY",
                        "models": ["fixture-tool-budget-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    observed = {}

    def fake_enroll_provider_channels(**kwargs):
        observed.update(kwargs)
        return {"status": "blocked", "reason_codes": ["test_only"]}

    monkeypatch.setattr(
        "axio_fusion_api.cli.enroll_provider_channels",
        fake_enroll_provider_channels,
    )
    assert fusion_cli_main(
        [
            "--provider-config-file",
            str(config_path),
            "enroll-providers",
            "--live",
            "--tool-probe-timeout",
            "7",
            "--tool-probe-max-models",
            "9",
            "--tool-probe-max-models-per-provider",
            "3",
            "--reasoning-probe-timeout",
            "11",
            "--reasoning-probe-max-models",
            "5",
            "--reasoning-probe-max-models-per-provider",
            "2",
            "--output-dir",
            str(tmp_path / "enrollment"),
        ]
    ) == 2
    capsys.readouterr()
    assert observed["tool_probe_timeout"] == 7.0
    assert observed["tool_probe_max_models"] == 9
    assert observed["tool_probe_max_models_per_provider"] == 3
    assert observed["calibrate_reasoning"] is True
    assert observed["reasoning_probe_timeout"] == 11.0
    assert observed["reasoning_probe_max_models"] == 5
    assert observed["reasoning_probe_max_models_per_provider"] == 2


def test_provider_level_manifest_without_models_blocks_stale_default_registry(
    tmp_path,
    monkeypatch,
    capsys,
):
    config_path = tmp_path / "discovery_only_channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-discovery-only-channel",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_DISCOVERY_BASE_URL",
                        "api_key_env": "FIXTURE_DISCOVERY_API_KEY",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    for env_name in (
        "AXIO_FUSION_REGISTRY_PATH",
        "AXIO_FUSION_MODELS",
        "AXIO_FUSION_PROVIDER_CONFIGS",
        "AXIO_FUSION_PROVIDERS_JSON",
        "AXIO_NVIDIA_MODELS",
        "AXIO_CPA_PLUS_MODELS",
        "AXIO_AISZ_MODELS",
        "AXIO_TOKENAPIS_MODELS",
    ):
        monkeypatch.delenv(env_name, raising=False)
    monkeypatch.setenv("AXIO_FUSION_PROVIDER_CONFIG_FILE", str(config_path))
    monkeypatch.setenv("FIXTURE_DISCOVERY_BASE_URL", "https://fixture-discovery.invalid/v1")
    monkeypatch.setenv("FIXTURE_DISCOVERY_API_KEY", "fixture-discovery-secret")

    profiles = load_registry()
    assert profiles == []

    assert fusion_cli_main(
        ["--provider-config-file", str(config_path), "provider-config-summary"]
    ) == 0
    payload = json.loads(capsys.readouterr().out)
    serialized = json.dumps(payload, ensure_ascii=False)

    assert payload["configured_static_profile_count"] == 0
    assert payload["runtime_registry_profile_count"] == 0
    assert payload["runtime_registry_source"] == "provider_config_requires_enrollment_or_explicit_registry"
    assert payload["runtime_registry_requires_enrollment"] is True
    assert payload["configuration_sources"]["provider_config_count"] == 1
    assert payload["network_calls_performed"] is False
    assert "fixture-discovery-only-channel" not in serialized
    assert "FIXTURE_DISCOVERY_BASE_URL" not in serialized
    assert "FIXTURE_DISCOVERY_API_KEY" not in serialized
    assert "https://fixture-discovery.invalid" not in serialized
    assert "fixture-discovery-secret" not in serialized
    assert str(config_path) not in serialized


def test_explicit_empty_registry_does_not_activate_portable_default_seed(
    tmp_path,
    monkeypatch,
):
    registry_path = tmp_path / "empty_runtime_registry.json"
    registry_path.write_text(json.dumps({"models": []}), encoding="utf-8")
    for env_name in (
        "AXIO_FUSION_REGISTRY_PATH",
        "AXIO_FUSION_PROVIDER_CONFIG_FILE",
        "AXIO_FUSION_PROVIDER_CONFIGS",
        "AXIO_FUSION_PROVIDERS_JSON",
        "AXIO_FUSION_MODELS",
    ):
        monkeypatch.delenv(env_name, raising=False)

    assert load_registry(registry_path) == []


def test_provider_enrollment_promotes_only_a_complete_operationally_calibrated_registry(tmp_path, monkeypatch):
    config_path = tmp_path / "channels.json"
    config_path.write_text(
        json.dumps(
            {
                "providers": [
                    {
                        "provider": "fixture-responses",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_RESPONSES_BASE_URL",
                        "api_key_env": "FIXTURE_RESPONSES_API_KEY",
                        "models": ["fixture-model"],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setenv("FIXTURE_RESPONSES_BASE_URL", "https://fixture.invalid/v1")
    monkeypatch.setenv("FIXTURE_RESPONSES_API_KEY", "fixture-secret")

    def fake_text_probe(**kwargs):
        assert kwargs["live"] is True
        return {
            "schema": "axio_fusion_api.exposed_provider_model_probe.v1",
            "mode": "live",
            "network_calls_performed": True,
            "discovered_model_count": 1,
            "candidate_model_count": 1,
            "probe_report": {
                "mode": "live",
                "available_count": 1,
                "probes": [
                    {
                        "provider": "fixture-responses",
                        "model": "fixture-model",
                        "api_format": "responses",
                        "base_url_env": "FIXTURE_RESPONSES_BASE_URL",
                        "api_key_env": "FIXTURE_RESPONSES_API_KEY",
                        "status": "available",
                        "probe_mode": "live",
                        "latency_ms": 14,
                        "output_sha256": "a" * 64,
                        "capabilities": {
                            "science_knowledge": 0.8,
                            "logic": 0.8,
                            "structured_output": 0.85,
                            "critique": 0.85,
                            "daily_work": 0.8,
                        },
                    }
                ],
            },
        }

    def fake_tool_probe(profiles, **kwargs):
        assert len(profiles) == 1
        assert kwargs["live"] is True
        return {
            "schema": "axio_fusion_api.provider_tool_probe.v1",
            "probe_kind": "tool_call",
            "mode": "live",
            "network_calls_performed": True,
            "model_count": 1,
            "tool_call_supported_count": 1,
            "text_only_count": 0,
            "unparseable_tool_call_count": 0,
            "protocol_failure_count": 0,
            "transport_failure_count": 0,
            "probes": [
                {
                    "provider": "fixture-responses",
                    "model": "fixture-model",
                    "profile_id": "fixture-responses/fixture-model",
                    "api_format": "responses",
                    "probe_kind": "tool_call",
                    "status": "tool_call_supported",
                    "latency_ms": 16,
                    "tool_call_count": 1,
                    "valid_tool_call_count": 1,
                }
            ],
        }

    monkeypatch.setattr(
        "axio_fusion_api.provider_enrollment.probe_exposed_provider_models",
        fake_text_probe,
    )
    monkeypatch.setattr(
        "axio_fusion_api.provider_enrollment.probe_provider_tool_support",
        fake_tool_probe,
    )

    result = enroll_provider_channels(
        config_path=config_path,
        output_dir=tmp_path / "enrollment",
        live=True,
        redact_provider_identifiers=True,
    )
    serialized = json.dumps(result, ensure_ascii=False)

    assert result["status"] == "ready"
    assert result["serving_registry"]["model_count"] == 1
    assert result["serving_registry"]["path_is_calibrated"] is True
    assert result["artifacts"]["serving_registry_path_sha256"]
    assert result["warning_codes"] == []
    assert "fixture-responses" not in serialized
    assert "fixture-model" not in serialized
    assert "fixture-secret" not in serialized


def _prefusion_runtime_profile():
    return normalize_profile(
        {
            "provider": "prefusion-runtime",
            "model": "prefusion-model",
            "canonical_model_id": "prefusion-model",
            "api_format": "responses",
            "base_url_env": "PREFUSION_RUNTIME_BASE_URL",
            "api_key_env": "PREFUSION_RUNTIME_API_KEY",
            "health": "available",
            "enabled": True,
            "capabilities": {axis: 0.8 for axis in CAPABILITY_AXES},
        }
    )


def _prefusion_research_output():
    return {
        "schema": model_screening.PREFUSION_RESEARCH_OUTPUT_SCHEMA,
        "ordered_models": [
            {
                "candidate_id": "candidate_0001",
                "rank": 1,
                "capability_summary": {
                    "overall": 0.85,
                    "axes": {axis: 0.85 for axis in CAPABILITY_AXES},
                    "strengths": ["bounded fixture evidence"],
                    "limitations": ["operational prior only"],
                },
                "allowed_roles": ["primary_solver", "structured_extraction"],
                "disallowed_roles": [],
                "confidence": 0.9,
                "source_evidence_ids": ["source_fixture"],
                "rationale": "This is an operational fixture prior, not a benchmark claim.",
            }
        ],
    }


def test_runtime_prefusion_gate_blocks_without_research_source(monkeypatch):
    profile = _prefusion_runtime_profile()
    monkeypatch.setattr(
        "axio_fusion_api.provider_enrollment.discover_runtime_profiles",
        lambda *args, **kwargs: {
            "status": "ready",
            "profiles": [profile],
            "provider_count": 1,
            "successful_provider_count": 1,
            "failed_provider_count": 0,
            "skipped_provider_count": 0,
            "empty_success_provider_count": 0,
            "report_status_counts": {"ok": 1},
            "warning_codes": [],
        },
    )
    result = enroll_runtime_channels(
        {"providers": []},
        live=True,
        require_prefusion=True,
        calibrate_tools=False,
    )

    assert result["status"] == "blocked"
    assert result["engine"] is None
    assert result["receipt"]["prefusion"]["required"] is True
    assert result["receipt"]["prefusion"]["status"] == "blocked"
    assert "prefusion_screening_blocked" in result["receipt"]["reason_codes"]
    assert "prefusion_public_source_fetch_empty" in result["receipt"]["reason_codes"]


def test_runtime_prefusion_gate_hands_only_bound_streaming_profiles_to_engine(monkeypatch):
    profile = _prefusion_runtime_profile()

    monkeypatch.setattr(
        "axio_fusion_api.provider_enrollment.discover_runtime_profiles",
        lambda *args, **kwargs: {
            "status": "ready",
            "profiles": [profile],
            "provider_count": 1,
            "successful_provider_count": 1,
            "failed_provider_count": 0,
            "skipped_provider_count": 0,
            "empty_success_provider_count": 0,
            "report_status_counts": {"ok": 1},
            "warning_codes": [],
        },
    )

    def fake_probe(profiles, **_kwargs):
        return {
            "schema": "axio_fusion_api.provider_probe.v1",
            "mode": "live",
            "network_calls_performed": True,
            "model_count": len(profiles),
            "available_count": len(profiles),
            "stream_requested_count": len(profiles),
            "stream_observed_count": len(profiles),
            "stream_fallback_count": 0,
            "probes": [
                {
                    "profile_id": item.profile_id,
                    "provider": item.provider,
                    "model": item.model,
                    "status": "available",
                    "latency_ms": 123,
                    "probe_mode": "live",
                    "live_probe_evidence": True,
                        "stream_requested": True,
                        "stream_observed": True,
                        "stream_fallback_used": False,
                        "stream_protocol": "sse",
                        "stream_frame_count": 2,
                        "strict_streaming_requested": True,
                        "output_sha256": sha256_text("fixture-stream"),
                }
                for item in profiles
            ],
        }

    monkeypatch.setattr(model_screening, "probe_provider_models", fake_probe)
    result = enroll_runtime_channels(
        {"providers": []},
        live=True,
        require_prefusion=True,
        source_manifest={
            "schema": model_screening.PREFUSION_SOURCE_MANIFEST_SCHEMA,
            "sources": [
                {
                    "source_slot": "source_fixture",
                    "content": "A bounded public-source fixture.",
                }
            ],
        },
        research_output=_prefusion_research_output(),
        calibrate_tools=False,
    )

    assert result["status"] == "ready"
    assert result["engine"] is not None
    assert [item.profile_id for item in result["profiles"]] == [profile.profile_id]
    assert result["receipt"]["prefusion"]["status"] == "ready"
    assert result["receipt"]["prefusion"]["available_logical_model_count"] == 1
    assert result["receipt"]["prefusion"]["eligible_physical_profile_count"] == 1
    assert result["receipt"]["prefusion"]["stream_observed_count"] == 1
    # Dynamic enrollment must consume the same fixed ranking and measured
    # latency metadata as a file-backed prefusion registry while preserving
    # credentials only on the in-memory profile object.
    enrolled = result["profiles"][0]
    assert enrolled.screening_prior_rank == 1
    assert enrolled.screening_operational_rank == 1
    assert enrolled.screening_operational_score is not None
    assert enrolled.screening_allowed_roles
    assert enrolled.p50_latency_ms == 123
    assert enrolled.p95_latency_ms == 123
    assert enrolled.source == "prefusion_stream_probe"
    serialized = json.dumps(result["receipt"], ensure_ascii=False)
    assert "prefusion-runtime" not in serialized
    assert "prefusion-model" not in serialized


def test_full_standalone_pytest_command_is_accepted_by_code_test_receipt():
    receipt = build_fusion_code_test_receipt(
        command_template="PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=src python3 -m pytest -q tests",
        exit_code=0,
        passed_count=382,
    )

    assert receipt["command_family"] == "standalone_fusion_pytest"
    assert receipt["ready_for_system_development_readiness"] is True
