"""Regression tests for the pre-Fusion model-list admission boundary."""

from __future__ import annotations

import json

import pytest

from axio_fusion_api.cli import main as standalone_cli_main
from axio_fusion_api.server import create_http_server, handle_request
from axio_fusion_api.service_cli import main as service_cli_main


def _write_legacy_registry(path) -> None:
    path.write_text(
        json.dumps(
            {
                "models": [
                    {
                        "provider": "legacy-provider",
                        "model": "legacy-model",
                        "api_format": "chat",
                        "base_url": "https://provider.invalid/v1",
                        "api_key": "fixture-secret",
                        "health": "available",
                        "enabled": True,
                    }
                ]
            }
        ),
        encoding="utf-8",
    )


@pytest.mark.parametrize("command", [standalone_cli_main, service_cli_main])
def test_live_complete_cli_requires_prefusion_generated_registry(tmp_path, command):
    registry_path = tmp_path / "legacy-registry.json"
    _write_legacy_registry(registry_path)

    with pytest.raises(ValueError, match="production serving requires a registry generated by pre-Fusion screening"):
        command(
            [
                "--registry",
                str(registry_path),
                "complete",
                "--prompt",
                "bounded live request",
                "--live",
            ]
        )


def test_live_http_factory_requires_prefusion_generated_registry(tmp_path, monkeypatch):
    registry_path = tmp_path / "legacy-registry.json"
    _write_legacy_registry(registry_path)
    monkeypatch.setenv("AXIO_FUSION_REGISTRY_PATH", str(registry_path))

    with pytest.raises(ValueError, match="production serving requires a registry generated by pre-Fusion screening"):
        create_http_server(host="127.0.0.1", port=0, live=True)


def test_live_request_without_injected_engine_cannot_bypass_prefusion(tmp_path, monkeypatch):
    registry_path = tmp_path / "legacy-registry.json"
    _write_legacy_registry(registry_path)
    monkeypatch.setenv("AXIO_FUSION_REGISTRY_PATH", str(registry_path))

    with pytest.raises(ValueError, match="production serving requires a registry generated by pre-Fusion screening"):
        handle_request(
            method="GET",
            path="/v1/health",
            headers={},
            body=b"",
            live=True,
            record_trace=False,
            record_runtime=False,
        )
